apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
  namespace: home
data:
  config: |-
    #use OpenDNS servers
    server=208.67.222.222
    server=208.67.220.220
    log-queries
  hosts: |
    127.0.0.1 localhost
