apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: home
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  template: 
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: ghcr.io/brainstain/docker-dnsmasq:master
          imagePullPolicy: Always
          ports: 
            - containerPort: 53
            - containerPort: 8080
          command: ["dnsmasq"]
          args: ["-d"]
          volumeMounts:
            - name: pvc-dns
              mountPath: /etc/dnsmasq.conf
              subPath: config
            - name: pvc-dns-hosts
              mountPath: /etc/hosts
              subPath: hosts
      volumes:
        - name: pvc-dns
          configMap:
            name: dns-config
            defaultMode: 0755
            items: 
              - key: config
                path: config
        - name: pvc-dns-hosts
          configMap:
            name: dns-config
            defaultMode: 0755
            items:
              - key: hosts
                path: hosts