apiVersion: v1
kind: Service
metadata:
  name: dnsmasq
  namespace: home
spec:
  type: LoadBalancer
  selector:
    app: dnsmasq
  ports:
    - name: udp 
      protocol: UDP
      port: 53
      targetPort: 53