apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-cert
  namespace: monitor
spec:
  dnsNames:
    - michaelgoldstein.co
    - '*.michaelgoldstein.co'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod-cert
