apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: ha-metrics
  namespace: monitor
spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: ha-token
    path: /api/prometheus
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    port: https
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __address__
        regex: (.*)
        replacement: "ha.michaelgoldstein.co:443"
        action: replace
  namespaceSelector:
    matchNames:
    - monitor
  selector:
    matchLabels:
      app: ha-service
---
kind: Service
apiVersion: v1
metadata:
  name: ha-service
  namespace: monitor
  labels:
    app: ha-service
spec:
  type: ExternalName
  externalName: ha.michaelgoldstein.co
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ha-service
  namespace: monitor
subsets:
  - addresses:
    - ip: 192.168.13.14
    ports:
    - name: https
      port: 443
      protocol: TCP