apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brainstain/home_deploy.git
    targetRevision: HEAD
    path: deployment/dns/overlay
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
