apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.5.0
    chart: loki-stack
    helm:
      parameters: 
      - name : loki.persistence.enabled
        value : "true"
      - name: loki.persistence.accessModes[0]
        value: ReadWriteOnce
      - name: loki.persistence.size
        value: 30Gi
      - name: loki.config.table_manager.retention_deletes_enabled
        value: "true"
      - name: loki.config.table_manager.retention_period
        value: 168h
      - name: loki.tolerations[0].key
        value: "arm64"
      - name: loki.tolerations[0].operator
        value: "Exists"
      - name: loki.tolerations[0].effect
        value: "PreferNoSchedule"
      - name: promtail.tolerations[0].key
        value: "node-role.kubernetes.io/master"
      - name: promtail.tolerations[0].operator
        value: "Exists"
      - name: promtail.tolerations[0].effect
        value: "NoSchedule"
      - name: promtail.tolerations[1].key
        value: "arm64"
      - name: promtail.tolerations[1].operator
        value: "Exists"
      - name: promtail.tolerations[1].effect
        value: "PreferNoSchedule"
      - name: promtail.extraScrapeConfigs[0].job_name
        value: "journal"
      - name: promtail.extraScrapeConfigs[0].journal.path
        value: "/var/log/journal"
      - name: promtail.extraScrapeConfigs[0].journal.max_age
        value: "12h"
      - name: promtail.extraScrapeConfigs[0].journal.labels.job
        value: "systemd-journal"
      - name: promtail.extraScrapeConfigs[0].relabel_configs[0].source_labels
        value: "['__journal__systemd_unit']"
      - name: promtail.extraScrapeConfigs[0].relabel_configs[0].target_label
        value: "unit"
      - name: promtail.extraScrapeConfigs[0].relabel_configs[1].source_labels
        value: "['__journal__hostname']"
      - name: promtail.extraScrapeConfigs[0].relabel_configs[1].target_label
        value: "['hostname']"
      - name: promtail.extraVolumes[0].name
        value: "journal"
      - name: promtail.extraVolumes[0].hostPath.path
        value: "/var/log/journal"
      - name: promtail.extraVolumeMounts[0].name
        value: "journal"
      - name: promtail.extraVolumeMounts[0].mountPath
        value: "/var/log/journal"
      - name: promtail.extraVolumeMounts[0].readOnly
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

