apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: 2.0.0
    chart: jupyterhub
    helm: 
     releaseName: jupyterhub
     parameters:
      - name: ingress.enabled
        value: "false"
      - name: images.pullPolicy
        value: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

