apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.5.0
    chart: loki-stack
    helm:
      parameters: 
      - name : loki.persistence.enabled
        value : "true"
      - name: loki.persistence.accessModes[0]
        value: ReadWriteOnce
      - name: loki.persistence.size
        value: 30Gi
      - name: loki.config.table_manager.retention_deletes_enabled
        value: "true"
      - name: loki.config.table_manager.retention_period
        value: 168h
      - name: loki.tolerations[0].key
        value: "arm64"
      - name: loki.tolerations[0].operator
        value: "Exists"
      - name: loki.tolerations[0].effect
        value: "PreferNoSchedule"
      - name: promtail.tolerations[0].key
        value: "node-role.kubernetes.io/master"
      - name: promtail.tolerations[0].operator
        value: "Exists"
      - name: promtail.tolerations[0].effect
        value: "NoSchedule"
      - name: promtail.tolerations[1].key
        value: "arm64"
      - name: promtail.tolerations[1].operator
        value: "Exists"
      - name: promtail.tolerations[1].effect
        value: "PreferNoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

