apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.0.11
    chart: jupyterhub
    helm: 
     releaseName: jupyterhub
     parameters:
      - name: ingress.enabled
        value: "false"
      - name: images.pullPolicy
        value: IfNotPresent
      - name: externalDatabase.host
        value: "acid-jupyterhub-postgresql"
      - name: postgresql.enabled
        value: "false"
      - name: postgresql.auth.username
        value: postgres
      - name: postgresql.auth.password
        value: password

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

