---
logrotate_conf_dir: "/etc/logrotate.d/"
logrotate_scripts: []
k3s_version: v1.24.17+k3s1 #v1.23.17+k3s1 # v1.25.16+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: '--resolv-conf /run/systemd/resolve/resolv.conf  --disable servicelb,local-storage,traefik'
extra_agent_args: '--resolv-conf /run/systemd/resolve/resolv.conf'
datastore_endpoint: ''
token: ''