apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres-operator-ui"
  labels:
    name: "postgres-operator-ui"
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: service
          env:
            - name: "TARGET_NAMESPACE"
              value: "*"
            - name: "TEAMS"
              value: |-
                [
                  "acid",
                  "rasa"
                ]