apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-node
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: "service"
          env:
            - name: "APP_URL"
              value: "http://localhost:8081"
            - name: "OPERATOR_API_URL"
              value: "http://postgres-operator:8080"
            - name: "OPERATOR_CLUSTER_NAME_LABEL"
              value: "cluster-name"
            #- name: "RESOURCES_VISIBLE"
            #  value: "False"
            #- name: "TARGET_NAMESPACE"
            #  value: "default"
            - name: "TEAMS"
              value: |-
                [
                  "rasa"
                ]
            - name: "OPERATOR_UI_CONFIG"
              value: |-
                {
                  "docs_link":"https://postgres-operator.readthedocs.io/en/latest/",
                  "dns_format_string": "{1}-{0}.{2}",
                  "databases_visible": true,
                  "master_load_balancer_visible": true,
                  "nat_gateways_visible": false,
                  "replica_load_balancer_visible": true,
                  "resources_visible": true,
                  "users_visible": true,
                  "cost_ebs": 0.119,
                  "cost_core": 0.0575,
                  "cost_memory": 0.014375,
                  "postgresql_versions": [
                    "14",
                    "13",
                    "12",
                    "11"
                  ]
                }