apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/zalando/postgres-operator/manifests?ref=v1.7.1
# - github.com/zalando/postgres-operator/ui/manifests?ref=v1.7.1

patches:
- path: deploymentSelectorPatch.yaml
  target:
    kind: Deployment
namespace: default