apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/zalando/postgres-operator/manifests?ref=v1.7.1
- github.com/zalando/postgres-operator/ui/manifests?ref=v1.7.1


namespace: default
patchesStrategicMerge:
  - deploymentSelectorPatch.yaml
  - |-
    apiVersion: "networking.k8s.io/v1"
    kind: "Ingress"
    metadata:
      name: "postgres-operator-ui"
      namespace: "default"
      labels:
        application: "postgres-operator-ui"
    $patch: delete