apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-jupyterhub-postgresql
  namespace: jupyter
spec:
  allowedSourceRanges: null
  databases:
    jupyter: postgres
  numberOfInstances: 2
  postgresql:
    version: '14'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    createdb: []
    postgres: []
    superuser: []
  volume:
    size: 10Gi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
