apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-external-db?ref=bc7c1e19ee18e080b97b9ca0ed3d144c57a30c73 # tag=0.12.0
- katib-mysql-secrets.yaml 

images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: docker.io/kubeflowkatib/katib-controller
    newTag: v0.12.0
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: docker.io/kubeflowkatib/katib-db-manager
    newTag: v0.12.0
  - name: docker.io/kubeflowkatib/katib-ui
    newName: docker.io/kubeflowkatib/katib-ui
    newTag: v0.12.0

patches:
- path: statefulSetSelectorPatch.yaml
  target:
    kind: StatefulSet
- path: deploymentSelectorPatch.yaml
  target:
    kind: Deployment

configurations:
  - sealed-secret-config.yaml