apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-external-db?ref=2a0b12eba755e4a47fa9d96e3102f31d5a25eebe 
- katib-mysql-secrets.yaml 
- katib-ingress.yaml 

images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: docker.io/kubeflowkatib/katib-controller
    newTag: v1beta1-2a0b12e
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: docker.io/kubeflowkatib/katib-db-manager
    newTag: v1beta1-2a0b12e
  - name: docker.io/kubeflowkatib/katib-ui
    newName: docker.io/kubeflowkatib/katib-ui
    newTag: v1beta1-2a0b12e
  - name: docker.io/kubeflowkatib/cert-generator
    newName: docker.io/kubeflowkatib/cert-generator
    newTag: v1beta1-2a0b12e

patches:
- path: statefulSetSelectorPatch.yaml
  target:
    kind: StatefulSet
- path: deploymentSelectorPatch.yaml
  target:
    kind: Deployment
- path: job-selector-patch.yaml
  target:
    kind: Job

configurations:
  - sealed-secret-config.yaml

secretGenerator:
  - name: katib-mysql-secrets
    behavior: replace 
    type: Opaque

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"