apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brainstain/home_lab.git
    targetRevision: HEAD
    path: ./deployment
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true