apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: home
  labels:
    app: dnsmasq
spec:
  replicas: 2
  template: 
    metadata:
      annotations:
        configHash: "3q4fds"
    spec:
      tolerations:
      - key: "arm64"
        operator: "Exists"
        effect: "PreferNoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - dnsmasq
                topologyKey: "kubernetes.io/hostname"
      