kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: photoprism-secrets
  namespace: home
  creationTimestamp: null
spec:
  template:
    metadata:
      name: photoprism-secrets
      namespace: home
      creationTimestamp: null
    data: null
  encryptedData:
    PHOTOPRISM_ADMIN_PASSWORD: AgB+XjUMaioNdWNX4ORD5j/AaIq+aSKqKJ05pZnj5hkBcPMsC5Wj1u+a4zlaIo15LQHNAneah9dz7v3bKzx7uKCTRwjiu9f9QE4USd+36dqHioQInqWxpj6nc+N63s/IJ++MocHSQfCS62dxDFb/lszlEPaInhCfvyRPgOspjyRx+n9sZ1VzaB/jStjRJmKC4Ihz40KoxRdLqxQIl17fLBoPFwdUE6bHiNnIccWsqCSFhUbAeaGO40O743vyyAxkOhYI/qF4NZeHt7CyfHf8uMnQNH9le4VEKubIECKODA6hv9rdNoC/DIxYdySz7h3Fy8cwjLcId7+M+lqQ/8fRTxL+WrzeV0NG6OAvxghvI0axMmZ+knrzk+/fGg3pMft/VKKikb3Ype15iEeYhcAQMsUTNkXW5IqL6HW8RQgjemOHVoIRIBR6RFb4Enkja5y9ygPTcYAU7WLHW1VKCoB0T1FgvNe6wqjl/GO4sfb045Q1Kq6XZ0uOQle8C32p8CpEujqQo8c0Z1OUKz/KWvmLwtw2kWavYJ+zGosE7c84pauoFbxz+3c1RvvooIyUWW33eR7pTrxnn2aepe2fsVUtbJohZq3QMon1IrRmfrqRX+cY34oBRXWLHoeNWv7AAHoFAflEkjtESlylWFDEXAZsQh678jdQlUdNnuX1iQ+t5k6/DBXydyEfwHXubjG1HStG/lYMSLMsX6Pu8A==
    PHOTOPRISM_DATABASE_DSN: AgATSWPxh5oZgMK8GkzhS7J1fgPnTkie0ri515WrrSY+l8gYfeGC2539fEgIjYKLLYLarSF0BZDeC4zYVyUB8+MTFOPLJzTus3feqIHNENerjtNeKG29zOMByME7xtvkvTj0AURpcq5jqyl/II5T0xBzR2ZOyqR6kbMJrrRdFVVvussIFyMuNSqF820EnS6uF/42nkXWQmdha2KmXcsXgAj4d46U7RU7oK4XOpZ9ouTUVubVo1a6G0Uz4rX3o/mGrkJlIZWIq2AYKh9RWOfd846wOXeoxp6vU9sWP8mFGi3CDMZu+ymNwzmDclXTiR27ooTiGykCBnY+uHah06x/8F15PDZsbPoIv0+TzBBfVtbuunCkz/7jbpqIfxgpKIFvpb87dCTP0ClzIeM3xX0ffvPCCDQBlSh5gv6a/EKFmwj94+kSy04ROysJoAgsXtZUCXKgoqoa1qJtL3aiSSXa9tqqX9Ozxjq7vkExWUpveH/i3aG+F2c4vQR0dbgvA+nrY7atwRBFtGB8i3wydnQD9Wp8yOI+OBsMT5ABO3AR4NmOXwDhkOTt5T5I3KVeFNuNm1NO6WF3Hm3ooAbR7B19lwsbstTAdYBarT+XgCG8FQxV5PtQTQWgCe/mTsIZ6nyhbB4ZR+oycLx/DcZTctAXGSJtlWJoDJyXcVoMdBpCdSTGUvL5PaYMnnE+MQW6d0mxjIORjyREDcW47zkVFajAxXiCgHComq+ZTx2//YXMdlDPXA7SKxLkUS5NBZaeZ9aIVSbzypqvgmQ9yVbMgBf72NxcF1v60S0TYLiKxkTelOUmd0jh5OXs1dLDhNXOFUIqrQBd
