apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/common/user-namespace/base?ref=b9526c9d935d111317789d56f7c57abc8fbe793c # Dec 21 2021
