apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitor
  labels:
    app: unpoller
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - monitor
  selector:
    matchLabels:
      app: unpoller # target gitlab service
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics